//variable to hold text string
var message = "catch me if you can!";
//variable to hold custom font
var font;
//variable to hold a textBox, to be generated by the textBounds() method
var textBox;
var fontsize = 100;
//these two 
var textX, textY;

//preload function used to load up a font that I really like
//courtesy of the League of Movable Type
//https://www.theleagueofmoveabletype.com/ostrich-sans
function preload() {
  font = loadFont('OstrichSans-Heavy.otf');
}

function setup() {
  createCanvas(windowWidth, windowHeight);
  //sets up and aligns
  textFont(font);
  textSize(fontsize);
  textAlign(CENTER);

  //sets up the
  textX = width/2;
  textY = height/2;

}

function draw() {
 //clears the background and prevents a trail of text from showing up
  background(244, 44, 4);

  fill(0);
  text(message, textX, textY);
  //to my understanding, the textBounds function returns an invisible rectangle
  //which is meant be the size of the text string
  //this box is used to check whether the mouse is hovering over the text or not
  textBox = font.textBounds(message,textX,textY,fontsize);

  // if statement which checks if the mouse position is INSIDE the textBox
  // if that's the case, the string "jumps" in any random direction within 200 pixels
  // of the original X and Y
  if ((mouseX >= textBox.x && mouseX <= textBox.x + textBox.w) &&
    (mouseY >= textBox.y && mouseY <= textBox.y + textBox.h)) {
    textX += random(-200, 200);
    textY += random(-200, 200);
  }
}
